name: nepali_english_calendar
description: A Flutter package for a dual Nepali (BS) and English (AD) calendar with toggle functionality.
version: 0.0.1
homepage: https://github.com/yourusername/nepali_english_calendar

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nepali_utils: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
